substitutions:
  device_name: l8balconeyesph
  friendly_name: "balconey_lanbon"

esphome:
  name: ${device_name}
  platformio_options:
    board_build.flash_mode: dio

esp32:
  board: esp32dev
  framework:
    type: arduino

# PSRAM configuration for ESP32-WROVER-B
psram:
  mode: octal
  speed: 80MHz

# Enable logging
logger:
  level: DEBUG

# Enable Home Assistant API
api:
  encryption:
    key: !secret api_encryption_key

ota:
  password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "${friendly_name} Fallback"
    password: !secret fallback_password

captive_portal:

# Enable Web server
web_server:
  port: 80

# I2C Bus for touch controller
i2c:
  sda: GPIO4
  scl: GPIO0
  scan: true

# SPI for the display
spi:
  clk_pin: GPIO19
  mosi_pin: GPIO23
  miso_pin: GPIO25

# Outputs (relays, backlight, mood light)
output:
  # Display backlight (PWM for brightness control)
  - platform: ledc
    pin: GPIO5
    id: backlight_pwm

  # RGB Mood Light
  - platform: ledc
    pin: GPIO26
    id: moodRed
  - platform: ledc
    pin: GPIO32
    id: moodGreen
  - platform: ledc
    pin: GPIO33
    id: moodBlue

  # Relays
  - platform: gpio
    pin: GPIO12
    id: relay_1
  - platform: gpio
    pin: GPIO14
    id: relay_2
  - platform: gpio
    pin: GPIO27
    id: relay_3

# Lights
light:
  # RGB Mood Light
  - platform: rgb
    name: "${friendly_name} Mood Light"
    id: mood_light
    red: moodRed
    green: moodGreen
    blue: moodBlue
    restore_mode: ALWAYS_OFF

  # Backlight with brightness control
  - platform: monochromatic
    name: "${friendly_name} Backlight"
    id: backlight
    output: backlight_pwm
    restore_mode: ALWAYS_ON

# ST7789V Display (240x320)
display:
  - id: lanbon_l8
    platform: ili9xxx
    model: ST7789V
    invert_colors: false
    dimensions: 240x320
    cs_pin: GPIO22
    dc_pin: GPIO21
    reset_pin: GPIO18
    auto_clear_enabled: false
    update_interval: never
    rotation: 180

# Fonts for display
font:
  - file: "fonts/Arial.ttf"
    id: font1
    size: 24

# Touch controller (FT6336)
touchscreen:
  platform: ft63x6
  id: lanbon_touchscreen
  calibration:
    x_min: 0
    y_min: 0
    x_max: 230
    y_max: 312
  on_touch:
    - lambda: |-
        ESP_LOGI("touch", "Touch at (%d, %d)", touch.x, touch.y);
  on_release:
    - if:
        condition: lvgl.is_paused
        then:
          - lvgl.resume:
          - lvgl.widget.redraw:
          - light.turn_on: backlight

# Relays (using output switches)
switch:
  - platform: output
    name: "${friendly_name} Relay 1"
    id: relay1
    output: relay_1
    restore_mode: RESTORE_DEFAULT_OFF

  - platform: output
    name: "${friendly_name} Relay 2"
    id: relay2
    output: relay_2
    restore_mode: RESTORE_DEFAULT_OFF

  - platform: output
    name: "${friendly_name} Relay 3"
    id: relay3
    output: relay_3
    restore_mode: RESTORE_DEFAULT_OFF

# LVGL UI Configuration
lvgl:
  displays:
    - lanbon_l8
  touchscreens:
    - lanbon_touchscreen

  # Auto-dim backlight after 10 seconds of inactivity
  on_idle:
    timeout: 10s
    then:
      - light.turn_off: backlight
      - lvgl.pause:

  # Example pages - customize as needed
  # pages:
  #   - id: main_page
  #     widgets:
  #       - label:
  #           text: "Lanbon L8"

# Sensors
sensor:
  # WiFi Signal Strength
  - platform: wifi_signal
    name: "${friendly_name} WiFi Signal"
    update_interval: 60s

  # Uptime
  - platform: uptime
    name: "${friendly_name} Uptime"
    update_interval: 60s

# Text sensors
text_sensor:
  - platform: wifi_info
    ip_address:
      name: "${friendly_name} IP Address"
    ssid:
      name: "${friendly_name} SSID"

  - platform: version
    name: "${friendly_name} ESPHome Version"
